<?php

/**
 * Implements hook_watchdog().
 */
function emaillog_watchdog(array $log_entry) {

  // Send email only if severity is one of WARNING, ERROR, CRITICAL, ALERT or
  // EMERGENCY.
  if ($log_entry['severity'] > WATCHDOG_WARNING) {
    return;
  }

  global $base_url, $language;

  $severity_list = watchdog_severity_levels();

  $to = variable_get('site_mail');
  $params = array();
  $params['subject'] = t('@site_name @severity_desc', array(
    '@site_name' => variable_get('site_name', 'Drupal'), 
    '@severity_desc' => $severity_list[$log_entry['severity']],
  ));

  // Replace message variables
  $message = t($log_entry['message'], $log_entry['variables']);

  $params['message']  = "\nSite:         @base_url";
  $params['message'] .= "\nSeverity:     (@severity) @severity_desc";
  $params['message'] .= "\nTimestamp:    @timestamp";
  $params['message'] .= "\nType:         @type";
  $params['message'] .= "\nIP Address:   @ip";
  $params['message'] .= "\nRequest URI:  @request_uri";
  $params['message'] .= "\nReferrer URI: @referer_uri";
  $params['message'] .= "\nUser:         (@uid) @name";
  if ($log_entry['link']) {
    $params['message'] .= "\nLink:         @link";
  }
  $params['message'] .= "\n\n\n" . strip_tags($message);

  $params['message'] = t($params['message'], array(
    '@base_url' => $base_url, 
    '@severity' => $log_entry['severity'], 
    '@severity_desc' => $severity_list[$log_entry['severity']], 
    '@timestamp' => format_date($log_entry['timestamp']), 
    '@type' => $log_entry['type'], 
    '@ip' => $log_entry['ip'], 
    '@request_uri' => $log_entry['request_uri'], 
    '@referer_uri' => $log_entry['referer'], 
    '@uid' => $log_entry['uid'], 
    '@name' => $log_entry['user']->name, 
    '@link' => strip_tags($log_entry['link']), 
  ));

  drupal_mail('emaillog', 'entry', $to, $language, $params);
}

/**
 * Implements hook_mail().
 */
function emaillog_mail($key, &$message, $params) {
  switch ($key) {
    case 'entry':
      $message['subject'] = $params['subject'];
      $message['body'][] = $params['message'];
      break;
  }
}
